<?php

namespace Bazofather\Gap;

use Bazofather\Interface\BazofatherBase;

class GapBot extends BazofatherBase
{
    public function __construct()
    {
        parent::__construct();

        // 272be48d4501a35f8b3b2c042feb4acbcd839d4d433c72c92855ec2174012c89
        $this->setBaseUrl("https://api.gap.im/");
    }

    public function getUpdates(): array
    {
        return parent::getUpdates(); // TODO: Change the autogenerated stub
    }


}
